---
title: "Projects"
---


## Theoretical Population Genetics Research at Georgetown University
[Link to my research poster](files/2018-POSTER-Earl-Zedd.pdf)

In 2018 I was invited to spend the summer in Washington, DC conducting independent undergraduate research under the supervision of a research advisor. 
I studied a published research paper in which the author identified a novel mathematical model of population genetics that was producing results inconsistent with theory.
I reverse-engineered author's model (which was implemented in Fortran) and identified a simplifying assumption made by the model.
I and another undergraduate researcher wrote a model in MATLAB that was able to explore this simplifying assumption and confirm that it was responsible the published article's controversial results.

## Agent-Based Modeling research at Texas A&M University
[Link to my research poster](files/2017-POSTER-Earl-Zedd.pdf)

In 2017 I was invited to spend the summer in College Station, Texas conducting independent undergraduate research under the supervision of a research advisor. I designed and implemented an agent-based model of urban water providers adapting to sea-level rise. (The purpose of this model was test the feasability of using agent-based modeling to improve the resiliency of uban water infrastructure to climate change.) I conducted interviews with South Florida water providers in order to determine the decision space of the model, programmed the model using custom Java classes and the AnyLogic modeling platform, and presented my results at the Uban Water Infrastructure Network's annual meeting in Fort Collins, Colorado.

## Improving an Agent-Based Model of Wolf-Sheep Predation
[Link to my project on GitHub](https://github.com/earlio/netlogo-wolfsheephex)

In 2016, as part of a term project for a course on Complexity and Emergence, I modified a NetLogo model of wolf-sheep predation to use a map based on hexagons rather than squares. I suspected that this would result in more realistic movement patterns by the model's agents. The new model produced population levels over time that more closely resembled a plot of classical predator-prey differential equations than did the original model, and (subjectively speaking) the rendered movement patterns of the wolf and sheep populations had a more natural appearance.
